name: Qt Quick Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y qt6-base-dev qt6-declarative-dev cmake ninja-build

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install qt6-default cmake ninja -y
          echo "CMAKE_PREFIX_PATH=$(qt6-dir)" >> $GITHUB_ENV

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install qt cmake ninja
          echo "CMAKE_PREFIX_PATH=$(brew --prefix qt)" >> $GITHUB_ENV

      - name: Configure CMake
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --parallel

      - name: Package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QtQuickApp-${{ matrix.os }}
          path: build/
